fix: bash

diff --git a/templates/.ontrack-gitlab-template.yml b/templates/.ontrack-gitlab-template.yml
--- a/templates/.ontrack-gitlab-template.yml
+++ b/templates/.ontrack-gitlab-template.yml
@@ -2,17 +2,17 @@
 .ontrack_setup:
    before_script: |
 
-      if [[ "${ONTRACK_URL}" == "" ]]
-      then
-        echo "Missing ONTRACK_URL variable."
-        exit 1
-      fi
+      # if [[ "${ONTRACK_URL}" == "" ]]
+      # then
+      #   echo "Missing ONTRACK_URL variable."
+      #   exit 1
+      # fi
 
-      if [[ "${ONTRACK_TOKEN}" == "" ]]
-      then
-        echo "Missing ONTRACK_TOKEN variable."
-        exit 1
-      fi
+      # if [[ "${ONTRACK_TOKEN}" == "" ]]
+      # then
+      #   echo "Missing ONTRACK_TOKEN variable."
+      #   exit 1
+      # fi
 
       if [[ "${ONTRACK_CLI_VERSION}" == "" ]]
       then
