chore: Ontrack CLI config

diff --git a/templates/.ontrack-gitlab-template.yml b/templates/.ontrack-gitlab-template.yml
--- a/templates/.ontrack-gitlab-template.yml
+++ b/templates/.ontrack-gitlab-template.yml
@@ -1,10 +1,23 @@
 # Setting up the Ontrack CLI
 .ontrack_setup:
    before_script: |
+
+      if [[ "${ONTRACK_URL} == "" "]]
+      then
+        echo "Missing ONTRACK_URL variable."
+        exit 1
+      fi
+
+      if [[ "${ONTRACK_TOKEN} == "" "]]
+      then
+        echo "Missing ONTRACK_TOKEN variable."
+        exit 1
+      fi
+
       if [[ "${ONTRACK_CLI_VERSION}" == "" ]]
       then
         echo "No ONTRACK_CLI_VERSION defined at project or group level, using 0.1.18 by default."
-        export ONTRACK_CLI_VERSION=0.1.18
+        export ONTRACK_CLI_VERSION=0.1.21
       fi
 
       export OS=$(uname -s | tr '[:upper:]' '[:lower:]')
@@ -21,3 +34,6 @@
 
       chmod u+x ontrack-cli
       ./ontrack-cli version --cli
+
+      echo "Setting up Ontrack config to ${ONTRACK_URL}"
+      ontrack-cli config create default ${ONTRACK_URL} --token ${ONTRACK_TOKEN}
